// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4w0ofJcSL2CO8Zie5-eDeV-HsqEZg1l4',
    appId: '1:582179527294:web:0a415981c881db4e81d62f',
    messagingSenderId: '582179527294',
    projectId: 'tabularasa-bf234',
    authDomain: 'tabularasa-bf234.firebaseapp.com',
    databaseURL: 'https://tabularasa-bf234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabularasa-bf234.appspot.com',
    measurementId: 'G-7MVCB0BXXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbw0JCEmBdap3vyYDl7DLI8GwsBG1CJqw',
    appId: '1:582179527294:android:211e876fc9bb7dea81d62f',
    messagingSenderId: '582179527294',
    projectId: 'tabularasa-bf234',
    databaseURL: 'https://tabularasa-bf234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabularasa-bf234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uEfVJ_LoLtWf5h2oOASA-mmQ3mmNkTM',
    appId: '1:582179527294:ios:b8371f36c35ea81d81d62f',
    messagingSenderId: '582179527294',
    projectId: 'tabularasa-bf234',
    databaseURL: 'https://tabularasa-bf234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabularasa-bf234.appspot.com',
    androidClientId: '582179527294-0qs56snhrm0a0c5telj24vsto6tqjiom.apps.googleusercontent.com',
    iosClientId: '582179527294-sfcnvon103nvmi4ldic36dhkfi9v24lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabularasaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uEfVJ_LoLtWf5h2oOASA-mmQ3mmNkTM',
    appId: '1:582179527294:ios:124151c87203894581d62f',
    messagingSenderId: '582179527294',
    projectId: 'tabularasa-bf234',
    databaseURL: 'https://tabularasa-bf234-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tabularasa-bf234.appspot.com',
    androidClientId: '582179527294-0qs56snhrm0a0c5telj24vsto6tqjiom.apps.googleusercontent.com',
    iosClientId: '582179527294-nke7om4f70etbj610611augmrob1lonk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabularasaApp.RunnerTests',
  );
}
